### ISSUE TITLE
DataTable

### ISSUE THREAD

**Issue by 1beb** [vnijs/shiny-site#3]
Have you had any experience displaying a dataTable using this Rmd methodology? Would you happen to have an example where the `renderDataTable({})`  happens in the Rmd?

**Comment by vnijs** [comment]
I'm going to push an expanded version of shiny-site in the next few weeks. That will have examples of other types of inputs, including DT tables.

**Comment by 1beb** [comment]
Ah that's great. I actually sorted it out myself using the example of the slider that you had plus uiOutput()
