### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by 1beb** [vnijs/shiny-site#5]
I think you're on to something here. There are a couple of things that I noticed. WIth the new getDeps() function, you no longer have to input more complicated elements into the server function, you can keep everything you need in one file. This is wildly easier than RStudios own method of abstracting sub-apps. You simply build a standalone application in Rmd, and you can reuse it by simply renaming it. It even allows you to abstract away from global. 

I've got this working with a password as well, would you like me to submit a branch that shows how to password protect?

**Comment by vnijs** [comment]
Adding password protection sounds great. I would be happy to accept a PR on master.

**Comment by 1beb** [comment]
The only problem is that I can't make it optional. So maybe a branch with password and without would be better?

**Comment by vnijs** [comment]
Could the password option be (de)activated setting a value through `options` in .Rprofile?
