### ISSUE TITLE
Including images in a .Rmd?

### ISSUE THREAD

**Issue by jwhendy** [vnijs/shiny-site#6]
Greetings, I've been really stuck on how to get `.Rmd` files rendered nicely in `shiny` and you've given me quite the start with this! It was so challenging to sort through all the various combinations/suggestions floating around out there between `renderMarkdown`, `knit()`, `includeMarkdown`, trying to go to `.md` first vs. raw `.Rmd`. So, many thanks for figuring this out/sharing.

I was trying to include an image and explored various avenues:
- standard: `![](image.png)`
- html: `<img src="image.png"/>`
- "shiny-ish" approach: `tags$div(img(src = "image.png"))`

All of them seem to just give me a broken link. It's not picking up a proper relative path, and if I copy/paste the image URL shown by the broken image icon, I get `http://127.0.0.1:5266/image.png`. If I knit it straight from RStudio, it shows up.

Any suggestions?

**Comment by vnijs** [comment]
Because it is a shiny app you'll want to put images etc. in the www/ directory of your app. I just added an example in page2.Rmd and put the image in www/images.

**Comment by jwhendy** [comment]
Awesome -- that helps tremendously. I'm guessing this is documented but I was just unaware. Thanks for the example, though what do you think of modifying it explicitly to instruct the use of the `www/` directory. Since the point of this repo _is_ for `.Rmd` in `shiny`, I think that would help things be more clear. For an example, maybe modify `page2.Rmd` to say something like:

> An image ... keep in mind that when running a shiny application, path references are with respect to the `www` directory at the same top level as `server.R` and `ui.R`. So a path to `images/Rlogo.png` in a `.Rmd` file would be stores inside of `www/images/` in the shiny application directory.
> 
> `![](images/Rlogo.png)`

**Comment by vnijs** [comment]
Done. Thanks for the suggestion @jwhendy
