### ISSUE TITLE
CJK/multibyte/Unicode support

### ISSUE THREAD

**Issue by nicholaelaw** [vnijs/shiny-site#7]
Hi there, great work! I shamelessly stole your code and put them to slavery.

But the web page is all messed up if I try to include non-ascii characters in the Rmd file. I added `encoding = "UTF-8"` to `markdownToHTML`, `readLines` and `knit2html`, and everything works fine. 

Of course this assumes that the document is encoded in UTF-8.

**Comment by vnijs** [comment]
Thanks for the suggestion @nicholaelaw. I just pushed an update. Please let me know if this works for you

**Comment by nicholaelaw** [comment]
Excellent work! Thanks!
